language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-dandule' ]; then cd .. && eval "mv $currentfolder generator-dandule" && cd generator-dandule; fi

